ND = 10
bins_per_2 = 0
total_time = 3000
n_step = 301
w_loss = 0
scg_loss = 0
dilution = 0
sat_pressure = 0
const_monomer = false
use_coag = true
calc_coefficients = true
calc_sink_params = true
grow_bey_bound = false
kernel = 1
RR = 5.0e6
temperature= 293.15
pressure = 1.01e5
rho = 1.47e3
m_mono = 2.4e-25
surface_tension = 64.5e-3