name = "section_soot"
version = "0.1.0"
license = "license"
author = "Joshua Christopher"
maintainer = "chrisjoshtopher@gmail.com"
copyright = "Copyright 2025, Joshua Christopher"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = true
source-form = "default"
[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
test-drive.tag = "v0.4.0"
[dependencies]
toml-f.git = "https://github.com/toml-f/toml-f"